//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlterTypeStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlterTypeStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}AlterTypeStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SchemaResolvedUserDefinedTypeName"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}AlterTypeAction"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlterTypeStatementType", propOrder = {
    "alterTypeStaticString",
    "schemaResolvedUserDefinedTypeName",
    "alterTypeAction"
})
public class AlterTypeStatementType {

    @XmlElement(name = "AlterTypeStaticString", required = true)
    protected AlterTypeStaticStringType alterTypeStaticString;
    @XmlElement(name = "SchemaResolvedUserDefinedTypeName", required = true)
    protected SchemaQualifiedTypeNameType schemaResolvedUserDefinedTypeName;
    @XmlElement(name = "AlterTypeAction", required = true)
    protected AlterTypeActionType alterTypeAction;

    /**
     * Gets the value of the alterTypeStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link AlterTypeStaticStringType }
     *     
     */
    public AlterTypeStaticStringType getAlterTypeStaticString() {
        return alterTypeStaticString;
    }

    /**
     * Sets the value of the alterTypeStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlterTypeStaticStringType }
     *     
     */
    public void setAlterTypeStaticString(AlterTypeStaticStringType value) {
        this.alterTypeStaticString = value;
    }

    /**
     * Gets the value of the schemaResolvedUserDefinedTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaQualifiedTypeNameType }
     *     
     */
    public SchemaQualifiedTypeNameType getSchemaResolvedUserDefinedTypeName() {
        return schemaResolvedUserDefinedTypeName;
    }

    /**
     * Sets the value of the schemaResolvedUserDefinedTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaQualifiedTypeNameType }
     *     
     */
    public void setSchemaResolvedUserDefinedTypeName(SchemaQualifiedTypeNameType value) {
        this.schemaResolvedUserDefinedTypeName = value;
    }

    /**
     * Gets the value of the alterTypeAction property.
     * 
     * @return
     *     possible object is
     *     {@link AlterTypeActionType }
     *     
     */
    public AlterTypeActionType getAlterTypeAction() {
        return alterTypeAction;
    }

    /**
     * Sets the value of the alterTypeAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlterTypeActionType }
     *     
     */
    public void setAlterTypeAction(AlterTypeActionType value) {
        this.alterTypeAction = value;
    }

}
