//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlterColumnActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlterColumnActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}SetColumnDefaultClause"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DropColumnDefaultClause"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}AddColumnScopeClause"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DropColumnScopeClause"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}AlterIdentityColumnSpecification"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlterColumnActionType", propOrder = {
    "setColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause"
})
public class AlterColumnActionType {

    @XmlElements({
        @XmlElement(name = "SetColumnDefaultClause", type = SetColumnDefaultClauseType.class),
        @XmlElement(name = "DropColumnDefaultClause", type = DropDefaultStaticStringType.class),
        @XmlElement(name = "AddColumnScopeClause", type = AddColumnScopeClauseType.class),
        @XmlElement(name = "DropColumnScopeClause", type = DropColumnScopeClauseType.class),
        @XmlElement(name = "AlterIdentityColumnSpecification", type = AlterIdentityColumnSpecificationType.class)
    })
    protected Object setColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause;

    /**
     * Gets the value of the setColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause property.
     * 
     * @return
     *     possible object is
     *     {@link SetColumnDefaultClauseType }
     *     {@link DropDefaultStaticStringType }
     *     {@link AddColumnScopeClauseType }
     *     {@link DropColumnScopeClauseType }
     *     {@link AlterIdentityColumnSpecificationType }
     *     
     */
    public Object getSetColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause() {
        return setColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause;
    }

    /**
     * Sets the value of the setColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetColumnDefaultClauseType }
     *     {@link DropDefaultStaticStringType }
     *     {@link AddColumnScopeClauseType }
     *     {@link DropColumnScopeClauseType }
     *     {@link AlterIdentityColumnSpecificationType }
     *     
     */
    public void setSetColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause(Object value) {
        this.setColumnDefaultClauseOrDropColumnDefaultClauseOrAddColumnScopeClause = value;
    }

}
