//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BooleanValueExpression_ISO9075ChoiceGroup1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BooleanValueExpression_ISO9075ChoiceGroup1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}BooleanValueExpression"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}OrStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}BooleanTerm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BooleanValueExpression_ISO9075ChoiceGroup1Type", propOrder = {
    "booleanValueExpression",
    "orStaticString",
    "booleanTerm"
})
public class BooleanValueExpressionISO9075ChoiceGroup1Type {

    @XmlElementRef(name = "BooleanValueExpression", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class)
    protected JAXBElement<BooleanValueExpressionType> booleanValueExpression;
    @XmlElement(name = "OrStaticString", required = true)
    protected OrStaticStringType orStaticString;
    @XmlElement(name = "BooleanTerm", required = true)
    protected BooleanTermType booleanTerm;

    /**
     * Gets the value of the booleanValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BooleanValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BooleanValueExpressionType }{@code >}
     *     
     */
    public JAXBElement<BooleanValueExpressionType> getBooleanValueExpression() {
        return booleanValueExpression;
    }

    /**
     * Sets the value of the booleanValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BooleanValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BooleanValueExpressionType }{@code >}
     *     
     */
    public void setBooleanValueExpression(JAXBElement<BooleanValueExpressionType> value) {
        this.booleanValueExpression = value;
    }

    /**
     * Gets the value of the orStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link OrStaticStringType }
     *     
     */
    public OrStaticStringType getOrStaticString() {
        return orStaticString;
    }

    /**
     * Sets the value of the orStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrStaticStringType }
     *     
     */
    public void setOrStaticString(OrStaticStringType value) {
        this.orStaticString = value;
    }

    /**
     * Gets the value of the booleanTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanTermType }
     *     
     */
    public BooleanTermType getBooleanTerm() {
        return booleanTerm;
    }

    /**
     * Sets the value of the booleanTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanTermType }
     *     
     */
    public void setBooleanTerm(BooleanTermType value) {
        this.booleanTerm = value;
    }

}
