//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterFactorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterFactorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}CharacterPrimary"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}CollateClause" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterFactorType", propOrder = {
    "characterPrimary",
    "collateClause"
})
public class CharacterFactorType {

    @XmlElement(name = "CharacterPrimary", required = true)
    protected CharacterPrimaryType characterPrimary;
    @XmlElement(name = "CollateClause")
    protected CollateClauseType collateClause;

    /**
     * Gets the value of the characterPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterPrimaryType }
     *     
     */
    public CharacterPrimaryType getCharacterPrimary() {
        return characterPrimary;
    }

    /**
     * Sets the value of the characterPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterPrimaryType }
     *     
     */
    public void setCharacterPrimary(CharacterPrimaryType value) {
        this.characterPrimary = value;
    }

    /**
     * Gets the value of the collateClause property.
     * 
     * @return
     *     possible object is
     *     {@link CollateClauseType }
     *     
     */
    public CollateClauseType getCollateClause() {
        return collateClause;
    }

    /**
     * Sets the value of the collateClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollateClauseType }
     *     
     */
    public void setCollateClause(CollateClauseType value) {
        this.collateClause = value;
    }

}
