//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColumnReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColumnReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}BasicIdentifierChain"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ColumnReference_ISO9075ChoiceGroup1"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnReferenceType", propOrder = {
    "basicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1"
})
public class ColumnReferenceType {

    @XmlElementRefs({
        @XmlElementRef(name = "BasicIdentifierChain", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ColumnReference_ISO9075ChoiceGroup1", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class, required = false)
    })
    protected JAXBElement<?> basicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1;

    /**
     * Gets the value of the basicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IdentifierChainType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdentifierChainType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ColumnReferenceISO9075ChoiceGroup1Type }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdentifierChainType }{@code >}
     *     
     */
    public JAXBElement<?> getBasicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1() {
        return basicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1;
    }

    /**
     * Sets the value of the basicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IdentifierChainType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdentifierChainType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ColumnReferenceISO9075ChoiceGroup1Type }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdentifierChainType }{@code >}
     *     
     */
    public void setBasicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1(JAXBElement<?> value) {
        this.basicIdentifierChainOrColumnReferenceISO9075ChoiceGroup1 = value;
    }

}
