//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CursorHoldabilityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CursorHoldabilityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WITH HOLD"/>
 *     &lt;enumeration value="WITHOUT HOLD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CursorHoldabilityType")
@XmlEnum
public enum CursorHoldabilityType {

    @XmlEnumValue("WITH HOLD")
    WITH_HOLD("WITH HOLD"),
    @XmlEnumValue("WITHOUT HOLD")
    WITHOUT_HOLD("WITHOUT HOLD");
    private final String value;

    CursorHoldabilityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CursorHoldabilityType fromValue(String v) {
        for (CursorHoldabilityType c: CursorHoldabilityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
