//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CursorSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CursorSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}QueryExpression"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}OrderByClause" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}UpdatabilityClause" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CursorSpecificationType", propOrder = {
    "queryExpression",
    "orderByClause",
    "updatabilityClause"
})
public class CursorSpecificationType {

    @XmlElement(name = "QueryExpression", required = true)
    protected QueryExpressionType queryExpression;
    @XmlElement(name = "OrderByClause")
    protected OrderByClauseType orderByClause;
    @XmlElement(name = "UpdatabilityClause")
    protected UpdatabilityClauseType updatabilityClause;

    /**
     * Gets the value of the queryExpression property.
     * 
     * @return
     *     possible object is
     *     {@link QueryExpressionType }
     *     
     */
    public QueryExpressionType getQueryExpression() {
        return queryExpression;
    }

    /**
     * Sets the value of the queryExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryExpressionType }
     *     
     */
    public void setQueryExpression(QueryExpressionType value) {
        this.queryExpression = value;
    }

    /**
     * Gets the value of the orderByClause property.
     * 
     * @return
     *     possible object is
     *     {@link OrderByClauseType }
     *     
     */
    public OrderByClauseType getOrderByClause() {
        return orderByClause;
    }

    /**
     * Sets the value of the orderByClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderByClauseType }
     *     
     */
    public void setOrderByClause(OrderByClauseType value) {
        this.orderByClause = value;
    }

    /**
     * Gets the value of the updatabilityClause property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatabilityClauseType }
     *     
     */
    public UpdatabilityClauseType getUpdatabilityClause() {
        return updatabilityClause;
    }

    /**
     * Sets the value of the updatabilityClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatabilityClauseType }
     *     
     */
    public void setUpdatabilityClause(UpdatabilityClauseType value) {
        this.updatabilityClause = value;
    }

}
