//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DelimitedIdentifierPartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DelimitedIdentifierPartType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}NondoublequoteCharacter"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DoublequoteSymbol"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DelimitedIdentifierPartType", propOrder = {
    "nondoublequoteCharacterOrDoublequoteSymbol"
})
public class DelimitedIdentifierPartType {

    @XmlElements({
        @XmlElement(name = "NondoublequoteCharacter", type = String.class),
        @XmlElement(name = "DoublequoteSymbol", type = DoublequoteSymbolType.class)
    })
    protected Object nondoublequoteCharacterOrDoublequoteSymbol;

    /**
     * Gets the value of the nondoublequoteCharacterOrDoublequoteSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     {@link DoublequoteSymbolType }
     *     
     */
    public Object getNondoublequoteCharacterOrDoublequoteSymbol() {
        return nondoublequoteCharacterOrDoublequoteSymbol;
    }

    /**
     * Sets the value of the nondoublequoteCharacterOrDoublequoteSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     {@link DoublequoteSymbolType }
     *     
     */
    public void setNondoublequoteCharacterOrDoublequoteSymbol(Object value) {
        this.nondoublequoteCharacterOrDoublequoteSymbol = value;
    }

}
