//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DerivedColumnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DerivedColumnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}ValueExpression"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}AsClause" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DerivedColumnType", propOrder = {
    "valueExpression",
    "asClause"
})
public class DerivedColumnType {

    @XmlElementRef(name = "ValueExpression", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class)
    protected JAXBElement<ValueExpressionType> valueExpression;
    @XmlElement(name = "AsClause")
    protected AsClauseType asClause;

    /**
     * Gets the value of the valueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     
     */
    public JAXBElement<ValueExpressionType> getValueExpression() {
        return valueExpression;
    }

    /**
     * Sets the value of the valueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ValueExpressionType }{@code >}
     *     
     */
    public void setValueExpression(JAXBElement<ValueExpressionType> value) {
        this.valueExpression = value;
    }

    /**
     * Gets the value of the asClause property.
     * 
     * @return
     *     possible object is
     *     {@link AsClauseType }
     *     
     */
    public AsClauseType getAsClause() {
        return asClause;
    }

    /**
     * Sets the value of the asClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsClauseType }
     *     
     */
    public void setAsClause(AsClauseType value) {
        this.asClause = value;
    }

}
