//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DropDomainStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DropDomainStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}DropDomainStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DomainName"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DropBehavior"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DropDomainStatementType", propOrder = {
    "dropDomainStaticString",
    "domainName",
    "dropBehavior"
})
public class DropDomainStatementType {

    @XmlElement(name = "DropDomainStaticString", required = true)
    protected DropDomainStaticStringType dropDomainStaticString;
    @XmlElement(name = "DomainName", required = true)
    protected SchemaQualifiedNameType domainName;
    @XmlElement(name = "DropBehavior", required = true)
    protected DropBehaviorType dropBehavior;

    /**
     * Gets the value of the dropDomainStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link DropDomainStaticStringType }
     *     
     */
    public DropDomainStaticStringType getDropDomainStaticString() {
        return dropDomainStaticString;
    }

    /**
     * Sets the value of the dropDomainStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropDomainStaticStringType }
     *     
     */
    public void setDropDomainStaticString(DropDomainStaticStringType value) {
        this.dropDomainStaticString = value;
    }

    /**
     * Gets the value of the domainName property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaQualifiedNameType }
     *     
     */
    public SchemaQualifiedNameType getDomainName() {
        return domainName;
    }

    /**
     * Sets the value of the domainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaQualifiedNameType }
     *     
     */
    public void setDomainName(SchemaQualifiedNameType value) {
        this.domainName = value;
    }

    /**
     * Gets the value of the dropBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link DropBehaviorType }
     *     
     */
    public DropBehaviorType getDropBehavior() {
        return dropBehavior;
    }

    /**
     * Sets the value of the dropBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropBehaviorType }
     *     
     */
    public void setDropBehavior(DropBehaviorType value) {
        this.dropBehavior = value;
    }

}
