//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DropTriggerStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DropTriggerStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}DropTriggerStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}TriggerName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DropTriggerStatementType", propOrder = {
    "dropTriggerStaticString",
    "triggerName"
})
public class DropTriggerStatementType {

    @XmlElement(name = "DropTriggerStaticString", required = true)
    protected DropTriggerStaticStringType dropTriggerStaticString;
    @XmlElement(name = "TriggerName", required = true)
    protected SchemaQualifiedNameType triggerName;

    /**
     * Gets the value of the dropTriggerStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link DropTriggerStaticStringType }
     *     
     */
    public DropTriggerStaticStringType getDropTriggerStaticString() {
        return dropTriggerStaticString;
    }

    /**
     * Sets the value of the dropTriggerStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropTriggerStaticStringType }
     *     
     */
    public void setDropTriggerStaticString(DropTriggerStaticStringType value) {
        this.dropTriggerStaticString = value;
    }

    /**
     * Gets the value of the triggerName property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaQualifiedNameType }
     *     
     */
    public SchemaQualifiedNameType getTriggerName() {
        return triggerName;
    }

    /**
     * Sets the value of the triggerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaQualifiedNameType }
     *     
     */
    public void setTriggerName(SchemaQualifiedNameType value) {
        this.triggerName = value;
    }

}
