//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DropSequenceGeneratorStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DropSequenceGeneratorStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}DropSequenceStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SequenceGeneratorName"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DropBehavior"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DropSequenceGeneratorStatementType", propOrder = {
    "dropSequenceStaticString",
    "sequenceGeneratorName",
    "dropBehavior"
})
public class DropSequenceGeneratorStatementType {

    @XmlElement(name = "DropSequenceStaticString", required = true)
    protected DropSequenceStaticStringType dropSequenceStaticString;
    @XmlElement(name = "SequenceGeneratorName", required = true)
    protected SchemaQualifiedNameType sequenceGeneratorName;
    @XmlElement(name = "DropBehavior", required = true)
    protected DropBehaviorType dropBehavior;

    /**
     * Gets the value of the dropSequenceStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link DropSequenceStaticStringType }
     *     
     */
    public DropSequenceStaticStringType getDropSequenceStaticString() {
        return dropSequenceStaticString;
    }

    /**
     * Sets the value of the dropSequenceStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropSequenceStaticStringType }
     *     
     */
    public void setDropSequenceStaticString(DropSequenceStaticStringType value) {
        this.dropSequenceStaticString = value;
    }

    /**
     * Gets the value of the sequenceGeneratorName property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaQualifiedNameType }
     *     
     */
    public SchemaQualifiedNameType getSequenceGeneratorName() {
        return sequenceGeneratorName;
    }

    /**
     * Sets the value of the sequenceGeneratorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaQualifiedNameType }
     *     
     */
    public void setSequenceGeneratorName(SchemaQualifiedNameType value) {
        this.sequenceGeneratorName = value;
    }

    /**
     * Gets the value of the dropBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link DropBehaviorType }
     *     
     */
    public DropBehaviorType getDropBehavior() {
        return dropBehavior;
    }

    /**
     * Sets the value of the dropBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropBehaviorType }
     *     
     */
    public void setDropBehavior(DropBehaviorType value) {
        this.dropBehavior = value;
    }

}
