//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExecuteImmediateStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExecuteImmediateStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}ExecuteImmediateStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SqlStatementVariable"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExecuteImmediateStatementType", propOrder = {
    "executeImmediateStaticString",
    "sqlStatementVariable"
})
public class ExecuteImmediateStatementType {

    @XmlElement(name = "ExecuteImmediateStaticString", required = true)
    protected ExecuteImmediateStaticStringType executeImmediateStaticString;
    @XmlElement(name = "SqlStatementVariable", required = true)
    protected SimpleValueSpecificationType sqlStatementVariable;

    /**
     * Gets the value of the executeImmediateStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link ExecuteImmediateStaticStringType }
     *     
     */
    public ExecuteImmediateStaticStringType getExecuteImmediateStaticString() {
        return executeImmediateStaticString;
    }

    /**
     * Sets the value of the executeImmediateStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecuteImmediateStaticStringType }
     *     
     */
    public void setExecuteImmediateStaticString(ExecuteImmediateStaticStringType value) {
        this.executeImmediateStaticString = value;
    }

    /**
     * Gets the value of the sqlStatementVariable property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleValueSpecificationType }
     *     
     */
    public SimpleValueSpecificationType getSqlStatementVariable() {
        return sqlStatementVariable;
    }

    /**
     * Sets the value of the sqlStatementVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleValueSpecificationType }
     *     
     */
    public void setSqlStatementVariable(SimpleValueSpecificationType value) {
        this.sqlStatementVariable = value;
    }

}
