//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenerationClauseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenerationClauseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}GenerationRule"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}AsStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}GenerationExpression"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenerationClauseType", propOrder = {
    "generationRule",
    "asStaticString",
    "generationExpression"
})
public class GenerationClauseType {

    @XmlElement(name = "GenerationRule", required = true)
    protected GenerationRuleType generationRule;
    @XmlElement(name = "AsStaticString", required = true)
    protected AsStaticStringType asStaticString;
    @XmlElement(name = "GenerationExpression", required = true)
    protected GenerationExpressionType generationExpression;

    /**
     * Gets the value of the generationRule property.
     * 
     * @return
     *     possible object is
     *     {@link GenerationRuleType }
     *     
     */
    public GenerationRuleType getGenerationRule() {
        return generationRule;
    }

    /**
     * Sets the value of the generationRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenerationRuleType }
     *     
     */
    public void setGenerationRule(GenerationRuleType value) {
        this.generationRule = value;
    }

    /**
     * Gets the value of the asStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link AsStaticStringType }
     *     
     */
    public AsStaticStringType getAsStaticString() {
        return asStaticString;
    }

    /**
     * Sets the value of the asStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsStaticStringType }
     *     
     */
    public void setAsStaticString(AsStaticStringType value) {
        this.asStaticString = value;
    }

    /**
     * Gets the value of the generationExpression property.
     * 
     * @return
     *     possible object is
     *     {@link GenerationExpressionType }
     *     
     */
    public GenerationExpressionType getGenerationExpression() {
        return generationExpression;
    }

    /**
     * Sets the value of the generationExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenerationExpressionType }
     *     
     */
    public void setGenerationExpression(GenerationExpressionType value) {
        this.generationExpression = value;
    }

}
