//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HavingClauseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HavingClauseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}HavingStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SearchCondition"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HavingClauseType", propOrder = {
    "havingStaticString",
    "searchCondition"
})
public class HavingClauseType {

    @XmlElement(name = "HavingStaticString", required = true)
    protected HavingStaticStringType havingStaticString;
    @XmlElement(name = "SearchCondition", required = true)
    protected BooleanValueExpressionType searchCondition;

    /**
     * Gets the value of the havingStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link HavingStaticStringType }
     *     
     */
    public HavingStaticStringType getHavingStaticString() {
        return havingStaticString;
    }

    /**
     * Sets the value of the havingStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link HavingStaticStringType }
     *     
     */
    public void setHavingStaticString(HavingStaticStringType value) {
        this.havingStaticString = value;
    }

    /**
     * Gets the value of the searchCondition property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanValueExpressionType }
     *     
     */
    public BooleanValueExpressionType getSearchCondition() {
        return searchCondition;
    }

    /**
     * Sets the value of the searchCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanValueExpressionType }
     *     
     */
    public void setSearchCondition(BooleanValueExpressionType value) {
        this.searchCondition = value;
    }

}
