//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InclusiveUserDefinedTypeSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InclusiveUserDefinedTypeSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}PathResolvedUserDefinedTypeName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InclusiveUserDefinedTypeSpecificationType", propOrder = {
    "pathResolvedUserDefinedTypeName"
})
public class InclusiveUserDefinedTypeSpecificationType {

    @XmlElementRef(name = "PathResolvedUserDefinedTypeName", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class)
    protected JAXBElement<SchemaQualifiedTypeNameType> pathResolvedUserDefinedTypeName;

    /**
     * Gets the value of the pathResolvedUserDefinedTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedTypeNameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedTypeNameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedTypeNameType }{@code >}
     *     
     */
    public JAXBElement<SchemaQualifiedTypeNameType> getPathResolvedUserDefinedTypeName() {
        return pathResolvedUserDefinedTypeName;
    }

    /**
     * Sets the value of the pathResolvedUserDefinedTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedTypeNameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedTypeNameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedTypeNameType }{@code >}
     *     
     */
    public void setPathResolvedUserDefinedTypeName(JAXBElement<SchemaQualifiedTypeNameType> value) {
        this.pathResolvedUserDefinedTypeName = value;
    }

}
