//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinedTableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JoinedTableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}CrossJoin"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}QualifiedJoin"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}NaturalJoin"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}UnionJoin"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JoinedTableType", propOrder = {
    "crossJoinOrQualifiedJoinOrNaturalJoin"
})
public class JoinedTableType {

    @XmlElements({
        @XmlElement(name = "CrossJoin", type = CrossJoinType.class),
        @XmlElement(name = "QualifiedJoin", type = QualifiedJoinType.class),
        @XmlElement(name = "NaturalJoin", type = NaturalJoinType.class),
        @XmlElement(name = "UnionJoin", type = UnionJoinType.class)
    })
    protected Object crossJoinOrQualifiedJoinOrNaturalJoin;

    /**
     * Gets the value of the crossJoinOrQualifiedJoinOrNaturalJoin property.
     * 
     * @return
     *     possible object is
     *     {@link CrossJoinType }
     *     {@link QualifiedJoinType }
     *     {@link NaturalJoinType }
     *     {@link UnionJoinType }
     *     
     */
    public Object getCrossJoinOrQualifiedJoinOrNaturalJoin() {
        return crossJoinOrQualifiedJoinOrNaturalJoin;
    }

    /**
     * Sets the value of the crossJoinOrQualifiedJoinOrNaturalJoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossJoinType }
     *     {@link QualifiedJoinType }
     *     {@link NaturalJoinType }
     *     {@link UnionJoinType }
     *     
     */
    public void setCrossJoinOrQualifiedJoinOrNaturalJoin(Object value) {
        this.crossJoinOrQualifiedJoinOrNaturalJoin = value;
    }

}
