//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinType_ISO9075ChoiceGroup1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JoinType_ISO9075ChoiceGroup1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}OuterJoinType"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}OuterStaticString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JoinType_ISO9075ChoiceGroup1Type", propOrder = {
    "outerJoinType",
    "outerStaticString"
})
public class JoinTypeISO9075ChoiceGroup1Type {

    @XmlElement(name = "OuterJoinType", required = true)
    protected OuterJoinTypeType outerJoinType;
    @XmlElement(name = "OuterStaticString")
    protected OuterStaticStringType outerStaticString;

    /**
     * Gets the value of the outerJoinType property.
     * 
     * @return
     *     possible object is
     *     {@link OuterJoinTypeType }
     *     
     */
    public OuterJoinTypeType getOuterJoinType() {
        return outerJoinType;
    }

    /**
     * Sets the value of the outerJoinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuterJoinTypeType }
     *     
     */
    public void setOuterJoinType(OuterJoinTypeType value) {
        this.outerJoinType = value;
    }

    /**
     * Gets the value of the outerStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link OuterStaticStringType }
     *     
     */
    public OuterStaticStringType getOuterStaticString() {
        return outerStaticString;
    }

    /**
     * Sets the value of the outerStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuterStaticStringType }
     *     
     */
    public void setOuterStaticString(OuterStaticStringType value) {
        this.outerStaticString = value;
    }

}
