//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JoinSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}JoinCondition"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}NamedColumnsJoin"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JoinSpecificationType", propOrder = {
    "joinConditionOrNamedColumnsJoin"
})
public class JoinSpecificationType {

    @XmlElements({
        @XmlElement(name = "JoinCondition", type = JoinConditionType.class),
        @XmlElement(name = "NamedColumnsJoin", type = NamedColumnsJoinType.class)
    })
    protected Object joinConditionOrNamedColumnsJoin;

    /**
     * Gets the value of the joinConditionOrNamedColumnsJoin property.
     * 
     * @return
     *     possible object is
     *     {@link JoinConditionType }
     *     {@link NamedColumnsJoinType }
     *     
     */
    public Object getJoinConditionOrNamedColumnsJoin() {
        return joinConditionOrNamedColumnsJoin;
    }

    /**
     * Sets the value of the joinConditionOrNamedColumnsJoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link JoinConditionType }
     *     {@link NamedColumnsJoinType }
     *     
     */
    public void setJoinConditionOrNamedColumnsJoin(Object value) {
        this.joinConditionOrNamedColumnsJoin = value;
    }

}
