//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocalHandlerDeclarationListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocalHandlerDeclarationListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}TerminatedLocalHandlerDeclaration" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalHandlerDeclarationListType", propOrder = {
    "terminatedLocalHandlerDeclaration"
})
public class LocalHandlerDeclarationListType {

    @XmlElement(name = "TerminatedLocalHandlerDeclaration", required = true)
    protected List<TerminatedLocalHandlerDeclarationType> terminatedLocalHandlerDeclaration;

    /**
     * Gets the value of the terminatedLocalHandlerDeclaration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terminatedLocalHandlerDeclaration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerminatedLocalHandlerDeclaration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TerminatedLocalHandlerDeclarationType }
     * 
     * 
     */
    public List<TerminatedLocalHandlerDeclarationType> getTerminatedLocalHandlerDeclaration() {
        if (terminatedLocalHandlerDeclaration == null) {
            terminatedLocalHandlerDeclaration = new ArrayList<TerminatedLocalHandlerDeclarationType>();
        }
        return this.terminatedLocalHandlerDeclaration;
    }

}
