//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModifiedFieldTargetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModifiedFieldTargetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}TargetSpecification"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ModifiedFieldTarget_ISO9075ChoiceGroup1"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ModifiedFieldReference"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModifiedFieldTargetType", propOrder = {
    "targetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference"
})
public class ModifiedFieldTargetType {

    @XmlElementRefs({
        @XmlElementRef(name = "ModifiedFieldReference", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TargetSpecification", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ModifiedFieldTarget_ISO9075ChoiceGroup1", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class, required = false)
    })
    protected JAXBElement<?> targetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference;

    /**
     * Gets the value of the targetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TargetSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TargetSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ModifiedFieldTargetISO9075ChoiceGroup1Type }{@code >}
     *     {@link JAXBElement }{@code <}{@link ModifiedFieldReferenceType }{@code >}
     *     
     */
    public JAXBElement<?> getTargetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference() {
        return targetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference;
    }

    /**
     * Sets the value of the targetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TargetSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TargetSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ModifiedFieldTargetISO9075ChoiceGroup1Type }{@code >}
     *     {@link JAXBElement }{@code <}{@link ModifiedFieldReferenceType }{@code >}
     *     
     */
    public void setTargetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference(JAXBElement<?> value) {
        this.targetSpecificationOrModifiedFieldTargetISO9075ChoiceGroup1OrModifiedFieldReference = value;
    }

}
