//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NationalCharacterStringType_ISO9075ChoiceGroup9Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NationalCharacterStringType_ISO9075ChoiceGroup9Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}NclobStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}LeftParen" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}LargeObjectLength" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RightParen" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NationalCharacterStringType_ISO9075ChoiceGroup9Type", propOrder = {
    "nclobStaticString",
    "leftParen",
    "largeObjectLength",
    "rightParen"
})
public class NationalCharacterStringTypeISO9075ChoiceGroup9Type {

    @XmlElement(name = "NclobStaticString", required = true)
    protected NclobStaticStringType nclobStaticString;
    @XmlElement(name = "LeftParen")
    protected String leftParen;
    @XmlElement(name = "LargeObjectLength")
    protected LargeObjectLengthType largeObjectLength;
    @XmlElement(name = "RightParen")
    protected String rightParen;

    /**
     * Gets the value of the nclobStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link NclobStaticStringType }
     *     
     */
    public NclobStaticStringType getNclobStaticString() {
        return nclobStaticString;
    }

    /**
     * Sets the value of the nclobStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link NclobStaticStringType }
     *     
     */
    public void setNclobStaticString(NclobStaticStringType value) {
        this.nclobStaticString = value;
    }

    /**
     * Gets the value of the leftParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftParen() {
        return leftParen;
    }

    /**
     * Sets the value of the leftParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftParen(String value) {
        this.leftParen = value;
    }

    /**
     * Gets the value of the largeObjectLength property.
     * 
     * @return
     *     possible object is
     *     {@link LargeObjectLengthType }
     *     
     */
    public LargeObjectLengthType getLargeObjectLength() {
        return largeObjectLength;
    }

    /**
     * Sets the value of the largeObjectLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link LargeObjectLengthType }
     *     
     */
    public void setLargeObjectLength(LargeObjectLengthType value) {
        this.largeObjectLength = value;
    }

    /**
     * Gets the value of the rightParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightParen() {
        return rightParen;
    }

    /**
     * Sets the value of the rightParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightParen(String value) {
        this.rightParen = value;
    }

}
