//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OverridingMethodSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OverridingMethodSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}OverridingStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}PartialMethodSpecification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OverridingMethodSpecificationType", propOrder = {
    "overridingStaticString",
    "partialMethodSpecification"
})
public class OverridingMethodSpecificationType {

    @XmlElement(name = "OverridingStaticString", required = true)
    protected OverridingStaticStringType overridingStaticString;
    @XmlElement(name = "PartialMethodSpecification", required = true)
    protected PartialMethodSpecificationType partialMethodSpecification;

    /**
     * Gets the value of the overridingStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link OverridingStaticStringType }
     *     
     */
    public OverridingStaticStringType getOverridingStaticString() {
        return overridingStaticString;
    }

    /**
     * Sets the value of the overridingStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverridingStaticStringType }
     *     
     */
    public void setOverridingStaticString(OverridingStaticStringType value) {
        this.overridingStaticString = value;
    }

    /**
     * Gets the value of the partialMethodSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link PartialMethodSpecificationType }
     *     
     */
    public PartialMethodSpecificationType getPartialMethodSpecification() {
        return partialMethodSpecification;
    }

    /**
     * Sets the value of the partialMethodSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartialMethodSpecificationType }
     *     
     */
    public void setPartialMethodSpecification(PartialMethodSpecificationType value) {
        this.partialMethodSpecification = value;
    }

}
