//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreparableSqlDataStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreparableSqlDataStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}DeleteStatementSearched"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DynamicSingleRowSelectStatement"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}InsertStatement"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DynamicSelectStatement"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}UpdateStatementSearched"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}MergeStatement"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}PreparableDynamicDeleteStatementPositioned"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}PreparableDynamicUpdateStatementPositioned"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreparableSqlDataStatementType", propOrder = {
    "deleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement"
})
public class PreparableSqlDataStatementType {

    @XmlElements({
        @XmlElement(name = "DeleteStatementSearched", type = DeleteStatementSearchedType.class),
        @XmlElement(name = "DynamicSingleRowSelectStatement", type = DynamicSingleRowSelectStatementType.class),
        @XmlElement(name = "InsertStatement", type = InsertStatementType.class),
        @XmlElement(name = "DynamicSelectStatement", type = CursorSpecificationType.class),
        @XmlElement(name = "UpdateStatementSearched", type = UpdateStatementSearchedType.class),
        @XmlElement(name = "MergeStatement", type = MergeStatementType.class),
        @XmlElement(name = "PreparableDynamicDeleteStatementPositioned", type = PreparableDynamicDeleteStatementPositionedType.class),
        @XmlElement(name = "PreparableDynamicUpdateStatementPositioned", type = PreparableDynamicUpdateStatementPositionedType.class)
    })
    protected Object deleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement;

    /**
     * Gets the value of the deleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteStatementSearchedType }
     *     {@link DynamicSingleRowSelectStatementType }
     *     {@link InsertStatementType }
     *     {@link CursorSpecificationType }
     *     {@link UpdateStatementSearchedType }
     *     {@link MergeStatementType }
     *     {@link PreparableDynamicDeleteStatementPositionedType }
     *     {@link PreparableDynamicUpdateStatementPositionedType }
     *     
     */
    public Object getDeleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement() {
        return deleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement;
    }

    /**
     * Sets the value of the deleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteStatementSearchedType }
     *     {@link DynamicSingleRowSelectStatementType }
     *     {@link InsertStatementType }
     *     {@link CursorSpecificationType }
     *     {@link UpdateStatementSearchedType }
     *     {@link MergeStatementType }
     *     {@link PreparableDynamicDeleteStatementPositionedType }
     *     {@link PreparableDynamicUpdateStatementPositionedType }
     *     
     */
    public void setDeleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement(Object value) {
        this.deleteStatementSearchedOrDynamicSingleRowSelectStatementOrInsertStatement = value;
    }

}
