//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryTermType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}NonJoinQueryTerm"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}JoinedTable"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryTermType", propOrder = {
    "nonJoinQueryTermOrJoinedTable"
})
public class QueryTermType {

    @XmlElements({
        @XmlElement(name = "NonJoinQueryTerm", type = NonJoinQueryTermType.class),
        @XmlElement(name = "JoinedTable", type = JoinedTableType.class)
    })
    protected Object nonJoinQueryTermOrJoinedTable;

    /**
     * Gets the value of the nonJoinQueryTermOrJoinedTable property.
     * 
     * @return
     *     possible object is
     *     {@link NonJoinQueryTermType }
     *     {@link JoinedTableType }
     *     
     */
    public Object getNonJoinQueryTermOrJoinedTable() {
        return nonJoinQueryTermOrJoinedTable;
    }

    /**
     * Sets the value of the nonJoinQueryTermOrJoinedTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonJoinQueryTermType }
     *     {@link JoinedTableType }
     *     
     */
    public void setNonJoinQueryTermOrJoinedTable(Object value) {
        this.nonJoinQueryTermOrJoinedTable = value;
    }

}
