//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceScopeCheckType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceScopeCheckType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}ReferencesAreStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}NotStaticString" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}CheckedStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}OnDeleteStaticString" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ReferenceScopeCheckAction" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceScopeCheckType", propOrder = {
    "referencesAreStaticString",
    "notStaticString",
    "checkedStaticString",
    "onDeleteStaticString",
    "referenceScopeCheckAction"
})
public class ReferenceScopeCheckType {

    @XmlElement(name = "ReferencesAreStaticString", required = true)
    protected ReferencesAreStaticStringType referencesAreStaticString;
    @XmlElement(name = "NotStaticString")
    protected NotStaticStringType notStaticString;
    @XmlElement(name = "CheckedStaticString", required = true)
    protected CheckedStaticStringType checkedStaticString;
    @XmlElement(name = "OnDeleteStaticString")
    protected OnDeleteStaticStringType onDeleteStaticString;
    @XmlElement(name = "ReferenceScopeCheckAction")
    protected ReferentialActionType referenceScopeCheckAction;

    /**
     * Gets the value of the referencesAreStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesAreStaticStringType }
     *     
     */
    public ReferencesAreStaticStringType getReferencesAreStaticString() {
        return referencesAreStaticString;
    }

    /**
     * Sets the value of the referencesAreStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesAreStaticStringType }
     *     
     */
    public void setReferencesAreStaticString(ReferencesAreStaticStringType value) {
        this.referencesAreStaticString = value;
    }

    /**
     * Gets the value of the notStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link NotStaticStringType }
     *     
     */
    public NotStaticStringType getNotStaticString() {
        return notStaticString;
    }

    /**
     * Sets the value of the notStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotStaticStringType }
     *     
     */
    public void setNotStaticString(NotStaticStringType value) {
        this.notStaticString = value;
    }

    /**
     * Gets the value of the checkedStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link CheckedStaticStringType }
     *     
     */
    public CheckedStaticStringType getCheckedStaticString() {
        return checkedStaticString;
    }

    /**
     * Sets the value of the checkedStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckedStaticStringType }
     *     
     */
    public void setCheckedStaticString(CheckedStaticStringType value) {
        this.checkedStaticString = value;
    }

    /**
     * Gets the value of the onDeleteStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link OnDeleteStaticStringType }
     *     
     */
    public OnDeleteStaticStringType getOnDeleteStaticString() {
        return onDeleteStaticString;
    }

    /**
     * Sets the value of the onDeleteStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnDeleteStaticStringType }
     *     
     */
    public void setOnDeleteStaticString(OnDeleteStaticStringType value) {
        this.onDeleteStaticString = value;
    }

    /**
     * Gets the value of the referenceScopeCheckAction property.
     * 
     * @return
     *     possible object is
     *     {@link ReferentialActionType }
     *     
     */
    public ReferentialActionType getReferenceScopeCheckAction() {
        return referenceScopeCheckAction;
    }

    /**
     * Sets the value of the referenceScopeCheckAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferentialActionType }
     *     
     */
    public void setReferenceScopeCheckAction(ReferentialActionType value) {
        this.referenceScopeCheckAction = value;
    }

}
