//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RepeatFactorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RepeatFactorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}LeftBrace"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}LowValue"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}UpperLimit" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RightBrace"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepeatFactorType", propOrder = {
    "leftBrace",
    "lowValue",
    "upperLimit",
    "rightBrace"
})
public class RepeatFactorType {

    @XmlElement(name = "LeftBrace", required = true)
    protected String leftBrace;
    @XmlElement(name = "LowValue", required = true)
    protected String lowValue;
    @XmlElement(name = "UpperLimit")
    protected UpperLimitType upperLimit;
    @XmlElement(name = "RightBrace", required = true)
    protected String rightBrace;

    /**
     * Gets the value of the leftBrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftBrace() {
        return leftBrace;
    }

    /**
     * Sets the value of the leftBrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftBrace(String value) {
        this.leftBrace = value;
    }

    /**
     * Gets the value of the lowValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowValue() {
        return lowValue;
    }

    /**
     * Sets the value of the lowValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowValue(String value) {
        this.lowValue = value;
    }

    /**
     * Gets the value of the upperLimit property.
     * 
     * @return
     *     possible object is
     *     {@link UpperLimitType }
     *     
     */
    public UpperLimitType getUpperLimit() {
        return upperLimit;
    }

    /**
     * Sets the value of the upperLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpperLimitType }
     *     
     */
    public void setUpperLimit(UpperLimitType value) {
        this.upperLimit = value;
    }

    /**
     * Gets the value of the rightBrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightBrace() {
        return rightBrace;
    }

    /**
     * Sets the value of the rightBrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightBrace(String value) {
        this.rightBrace = value;
    }

}
