//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResignalStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResignalStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}ResignalStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SignalValue" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SetSignalInformation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResignalStatementType", propOrder = {
    "resignalStaticString",
    "signalValue",
    "setSignalInformation"
})
public class ResignalStatementType {

    @XmlElement(name = "ResignalStaticString", required = true)
    protected ResignalStaticStringType resignalStaticString;
    @XmlElement(name = "SignalValue")
    protected SignalValueType signalValue;
    @XmlElement(name = "SetSignalInformation")
    protected SetSignalInformationType setSignalInformation;

    /**
     * Gets the value of the resignalStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link ResignalStaticStringType }
     *     
     */
    public ResignalStaticStringType getResignalStaticString() {
        return resignalStaticString;
    }

    /**
     * Sets the value of the resignalStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResignalStaticStringType }
     *     
     */
    public void setResignalStaticString(ResignalStaticStringType value) {
        this.resignalStaticString = value;
    }

    /**
     * Gets the value of the signalValue property.
     * 
     * @return
     *     possible object is
     *     {@link SignalValueType }
     *     
     */
    public SignalValueType getSignalValue() {
        return signalValue;
    }

    /**
     * Sets the value of the signalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalValueType }
     *     
     */
    public void setSignalValue(SignalValueType value) {
        this.signalValue = value;
    }

    /**
     * Gets the value of the setSignalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link SetSignalInformationType }
     *     
     */
    public SetSignalInformationType getSetSignalInformation() {
        return setSignalInformation;
    }

    /**
     * Sets the value of the setSignalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetSignalInformationType }
     *     
     */
    public void setSetSignalInformation(SetSignalInformationType value) {
        this.setSignalInformation = value;
    }

}
