//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoutineTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoutineTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}RoutineStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}FunctionStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ProcedureStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RoutineType_ISO9075ChoiceGroup1"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutineTypeType", propOrder = {
    "routineStaticStringOrFunctionStaticStringOrProcedureStaticString"
})
public class RoutineTypeType {

    @XmlElements({
        @XmlElement(name = "RoutineStaticString", type = RoutineStaticStringType.class),
        @XmlElement(name = "FunctionStaticString", type = FunctionStaticStringType.class),
        @XmlElement(name = "ProcedureStaticString", type = ProcedureStaticStringType.class),
        @XmlElement(name = "RoutineType_ISO9075ChoiceGroup1", type = RoutineTypeISO9075ChoiceGroup1Type.class)
    })
    protected Object routineStaticStringOrFunctionStaticStringOrProcedureStaticString;

    /**
     * Gets the value of the routineStaticStringOrFunctionStaticStringOrProcedureStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link RoutineStaticStringType }
     *     {@link FunctionStaticStringType }
     *     {@link ProcedureStaticStringType }
     *     {@link RoutineTypeISO9075ChoiceGroup1Type }
     *     
     */
    public Object getRoutineStaticStringOrFunctionStaticStringOrProcedureStaticString() {
        return routineStaticStringOrFunctionStaticStringOrProcedureStaticString;
    }

    /**
     * Sets the value of the routineStaticStringOrFunctionStaticStringOrProcedureStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutineStaticStringType }
     *     {@link FunctionStaticStringType }
     *     {@link ProcedureStaticStringType }
     *     {@link RoutineTypeISO9075ChoiceGroup1Type }
     *     
     */
    public void setRoutineStaticStringOrFunctionStaticStringOrProcedureStaticString(Object value) {
        this.routineStaticStringOrFunctionStaticStringOrProcedureStaticString = value;
    }

}
