//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RowTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RowTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}RowStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RowTypeBody"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RowTypeType", propOrder = {
    "rowStaticString",
    "rowTypeBody"
})
public class RowTypeType {

    @XmlElement(name = "RowStaticString", required = true)
    protected RowStaticStringType rowStaticString;
    @XmlElement(name = "RowTypeBody", required = true)
    protected RowTypeBodyType rowTypeBody;

    /**
     * Gets the value of the rowStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link RowStaticStringType }
     *     
     */
    public RowStaticStringType getRowStaticString() {
        return rowStaticString;
    }

    /**
     * Sets the value of the rowStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowStaticStringType }
     *     
     */
    public void setRowStaticString(RowStaticStringType value) {
        this.rowStaticString = value;
    }

    /**
     * Gets the value of the rowTypeBody property.
     * 
     * @return
     *     possible object is
     *     {@link RowTypeBodyType }
     *     
     */
    public RowTypeBodyType getRowTypeBody() {
        return rowTypeBody;
    }

    /**
     * Sets the value of the rowTypeBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowTypeBodyType }
     *     
     */
    public void setRowTypeBody(RowTypeBodyType value) {
        this.rowTypeBody = value;
    }

}
