//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchOrCycleClause_ISO9075ChoiceGroup1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchOrCycleClause_ISO9075ChoiceGroup1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}SearchClause2"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}CycleClause2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchOrCycleClause_ISO9075ChoiceGroup1Type", propOrder = {
    "searchClause2",
    "cycleClause2"
})
public class SearchOrCycleClauseISO9075ChoiceGroup1Type {

    @XmlElement(name = "SearchClause2", required = true)
    protected SearchClauseType searchClause2;
    @XmlElement(name = "CycleClause2", required = true)
    protected CycleClauseType cycleClause2;

    /**
     * Gets the value of the searchClause2 property.
     * 
     * @return
     *     possible object is
     *     {@link SearchClauseType }
     *     
     */
    public SearchClauseType getSearchClause2() {
        return searchClause2;
    }

    /**
     * Sets the value of the searchClause2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchClauseType }
     *     
     */
    public void setSearchClause2(SearchClauseType value) {
        this.searchClause2 = value;
    }

    /**
     * Gets the value of the cycleClause2 property.
     * 
     * @return
     *     possible object is
     *     {@link CycleClauseType }
     *     
     */
    public CycleClauseType getCycleClause2() {
        return cycleClause2;
    }

    /**
     * Sets the value of the cycleClause2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CycleClauseType }
     *     
     */
    public void setCycleClause2(CycleClauseType value) {
        this.cycleClause2 = value;
    }

}
