//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SetConnectionStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetConnectionStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}SetConnectionStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ConnectionObject"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetConnectionStatementType", propOrder = {
    "setConnectionStaticString",
    "connectionObject"
})
public class SetConnectionStatementType {

    @XmlElement(name = "SetConnectionStaticString", required = true)
    protected SetConnectionStaticStringType setConnectionStaticString;
    @XmlElement(name = "ConnectionObject", required = true)
    protected ConnectionObjectType connectionObject;

    /**
     * Gets the value of the setConnectionStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link SetConnectionStaticStringType }
     *     
     */
    public SetConnectionStaticStringType getSetConnectionStaticString() {
        return setConnectionStaticString;
    }

    /**
     * Sets the value of the setConnectionStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetConnectionStaticStringType }
     *     
     */
    public void setSetConnectionStaticString(SetConnectionStaticStringType value) {
        this.setConnectionStaticString = value;
    }

    /**
     * Gets the value of the connectionObject property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionObjectType }
     *     
     */
    public ConnectionObjectType getConnectionObject() {
        return connectionObject;
    }

    /**
     * Sets the value of the connectionObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionObjectType }
     *     
     */
    public void setConnectionObject(ConnectionObjectType value) {
        this.connectionObject = value;
    }

}
