//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalInformationItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalInformationItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}ConditionInformationItemName"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}EqualsOperator"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SimpleValueSpecification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalInformationItemType", propOrder = {
    "conditionInformationItemName",
    "equalsOperator",
    "simpleValueSpecification"
})
public class SignalInformationItemType {

    @XmlElement(name = "ConditionInformationItemName", required = true)
    protected ConditionInformationItemNameType conditionInformationItemName;
    @XmlElement(name = "EqualsOperator", required = true)
    protected String equalsOperator;
    @XmlElementRef(name = "SimpleValueSpecification", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class)
    protected JAXBElement<SimpleValueSpecificationType> simpleValueSpecification;

    /**
     * Gets the value of the conditionInformationItemName property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionInformationItemNameType }
     *     
     */
    public ConditionInformationItemNameType getConditionInformationItemName() {
        return conditionInformationItemName;
    }

    /**
     * Sets the value of the conditionInformationItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionInformationItemNameType }
     *     
     */
    public void setConditionInformationItemName(ConditionInformationItemNameType value) {
        this.conditionInformationItemName = value;
    }

    /**
     * Gets the value of the equalsOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEqualsOperator() {
        return equalsOperator;
    }

    /**
     * Sets the value of the equalsOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEqualsOperator(String value) {
        this.equalsOperator = value;
    }

    /**
     * Gets the value of the simpleValueSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     
     */
    public JAXBElement<SimpleValueSpecificationType> getSimpleValueSpecification() {
        return simpleValueSpecification;
    }

    /**
     * Sets the value of the simpleValueSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SimpleValueSpecificationType }{@code >}
     *     
     */
    public void setSimpleValueSpecification(JAXBElement<SimpleValueSpecificationType> value) {
        this.simpleValueSpecification = value;
    }

}
