//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SqlSchemaStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SqlSchemaStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}SqlSchemaDefinitionStatement"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SqlSchemaManipulationStatement"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SqlSchemaStatementType", propOrder = {
    "sqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement"
})
public class SqlSchemaStatementType {

    @XmlElements({
        @XmlElement(name = "SqlSchemaDefinitionStatement", type = SqlSchemaDefinitionStatementType.class),
        @XmlElement(name = "SqlSchemaManipulationStatement", type = SqlSchemaManipulationStatementType.class)
    })
    protected Object sqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement;

    /**
     * Gets the value of the sqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement property.
     * 
     * @return
     *     possible object is
     *     {@link SqlSchemaDefinitionStatementType }
     *     {@link SqlSchemaManipulationStatementType }
     *     
     */
    public Object getSqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement() {
        return sqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement;
    }

    /**
     * Sets the value of the sqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlSchemaDefinitionStatementType }
     *     {@link SqlSchemaManipulationStatementType }
     *     
     */
    public void setSqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement(Object value) {
        this.sqlSchemaDefinitionStatementOrSqlSchemaManipulationStatement = value;
    }

}
