//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TablePrimaryOrJoinedTableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TablePrimaryOrJoinedTableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}TablePrimary"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}JoinedTable"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TablePrimaryOrJoinedTableType", propOrder = {
    "tablePrimaryOrJoinedTable"
})
public class TablePrimaryOrJoinedTableType {

    @XmlElements({
        @XmlElement(name = "TablePrimary", type = TablePrimaryType.class),
        @XmlElement(name = "JoinedTable", type = JoinedTableType.class)
    })
    protected Object tablePrimaryOrJoinedTable;

    /**
     * Gets the value of the tablePrimaryOrJoinedTable property.
     * 
     * @return
     *     possible object is
     *     {@link TablePrimaryType }
     *     {@link JoinedTableType }
     *     
     */
    public Object getTablePrimaryOrJoinedTable() {
        return tablePrimaryOrJoinedTable;
    }

    /**
     * Sets the value of the tablePrimaryOrJoinedTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TablePrimaryType }
     *     {@link JoinedTableType }
     *     
     */
    public void setTablePrimaryOrJoinedTable(Object value) {
        this.tablePrimaryOrJoinedTable = value;
    }

}
