//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableValueConstructorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableValueConstructorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}ValuesStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RowValueExpressionList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableValueConstructorType", propOrder = {
    "valuesStaticString",
    "rowValueExpressionList"
})
public class TableValueConstructorType {

    @XmlElement(name = "ValuesStaticString", required = true)
    protected ValuesStaticStringType valuesStaticString;
    @XmlElement(name = "RowValueExpressionList", required = true)
    protected RowValueExpressionListType rowValueExpressionList;

    /**
     * Gets the value of the valuesStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link ValuesStaticStringType }
     *     
     */
    public ValuesStaticStringType getValuesStaticString() {
        return valuesStaticString;
    }

    /**
     * Sets the value of the valuesStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuesStaticStringType }
     *     
     */
    public void setValuesStaticString(ValuesStaticStringType value) {
        this.valuesStaticString = value;
    }

    /**
     * Gets the value of the rowValueExpressionList property.
     * 
     * @return
     *     possible object is
     *     {@link RowValueExpressionListType }
     *     
     */
    public RowValueExpressionListType getRowValueExpressionList() {
        return rowValueExpressionList;
    }

    /**
     * Sets the value of the rowValueExpressionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowValueExpressionListType }
     *     
     */
    public void setRowValueExpressionList(RowValueExpressionListType value) {
        this.rowValueExpressionList = value;
    }

}
