//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Term_ISO9075ChoiceGroup2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Term_ISO9075ChoiceGroup2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}Solidus"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}Factor"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Term_ISO9075ChoiceGroup2Type", propOrder = {
    "solidus",
    "factor"
})
public class TermISO9075ChoiceGroup2Type {

    @XmlElement(name = "Solidus", required = true)
    protected String solidus;
    @XmlElement(name = "Factor", required = true)
    protected FactorType factor;

    /**
     * Gets the value of the solidus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolidus() {
        return solidus;
    }

    /**
     * Sets the value of the solidus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolidus(String value) {
        this.solidus = value;
    }

    /**
     * Gets the value of the factor property.
     * 
     * @return
     *     possible object is
     *     {@link FactorType }
     *     
     */
    public FactorType getFactor() {
        return factor;
    }

    /**
     * Sets the value of the factor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FactorType }
     *     
     */
    public void setFactor(FactorType value) {
        this.factor = value;
    }

}
