//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeZoneIntervalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeZoneIntervalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}Sign"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}HoursValue"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}Colon"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}MinutesValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeZoneIntervalType", propOrder = {
    "sign",
    "hoursValue",
    "colon",
    "minutesValue"
})
public class TimeZoneIntervalType {

    @XmlElement(name = "Sign", required = true)
    protected SignType sign;
    @XmlElement(name = "HoursValue", required = true)
    protected String hoursValue;
    @XmlElement(name = "Colon", required = true)
    protected String colon;
    @XmlElement(name = "MinutesValue", required = true)
    protected String minutesValue;

    /**
     * Gets the value of the sign property.
     * 
     * @return
     *     possible object is
     *     {@link SignType }
     *     
     */
    public SignType getSign() {
        return sign;
    }

    /**
     * Sets the value of the sign property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignType }
     *     
     */
    public void setSign(SignType value) {
        this.sign = value;
    }

    /**
     * Gets the value of the hoursValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoursValue() {
        return hoursValue;
    }

    /**
     * Sets the value of the hoursValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoursValue(String value) {
        this.hoursValue = value;
    }

    /**
     * Gets the value of the colon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColon() {
        return colon;
    }

    /**
     * Sets the value of the colon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColon(String value) {
        this.colon = value;
    }

    /**
     * Gets the value of the minutesValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinutesValue() {
        return minutesValue;
    }

    /**
     * Sets the value of the minutesValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinutesValue(String value) {
        this.minutesValue = value;
    }

}
