//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeZoneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeZoneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}AtStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}TimeZoneSpecifier"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeZoneType", propOrder = {
    "atStaticString",
    "timeZoneSpecifier"
})
public class TimeZoneType {

    @XmlElement(name = "AtStaticString", required = true)
    protected AtStaticStringType atStaticString;
    @XmlElement(name = "TimeZoneSpecifier", required = true)
    protected TimeZoneSpecifierType timeZoneSpecifier;

    /**
     * Gets the value of the atStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link AtStaticStringType }
     *     
     */
    public AtStaticStringType getAtStaticString() {
        return atStaticString;
    }

    /**
     * Sets the value of the atStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtStaticStringType }
     *     
     */
    public void setAtStaticString(AtStaticStringType value) {
        this.atStaticString = value;
    }

    /**
     * Gets the value of the timeZoneSpecifier property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZoneSpecifierType }
     *     
     */
    public TimeZoneSpecifierType getTimeZoneSpecifier() {
        return timeZoneSpecifier;
    }

    /**
     * Sets the value of the timeZoneSpecifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZoneSpecifierType }
     *     
     */
    public void setTimeZoneSpecifier(TimeZoneSpecifierType value) {
        this.timeZoneSpecifier = value;
    }

}
