//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransliterationDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransliterationDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}CreateTranslationStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}TransliterationName"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ForStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SourceCharacterSetSpecification"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ToStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}TargetCharacterSetSpecification"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}FromStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}TransliterationSource"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransliterationDefinitionType", propOrder = {
    "createTranslationStaticString",
    "transliterationName",
    "forStaticString",
    "sourceCharacterSetSpecification",
    "toStaticString",
    "targetCharacterSetSpecification",
    "fromStaticString",
    "transliterationSource"
})
public class TransliterationDefinitionType {

    @XmlElement(name = "CreateTranslationStaticString", required = true)
    protected CreateTranslationStaticStringType createTranslationStaticString;
    @XmlElementRef(name = "TransliterationName", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class)
    protected JAXBElement<SchemaQualifiedNameType> transliterationName;
    @XmlElement(name = "ForStaticString", required = true)
    protected ForStaticStringType forStaticString;
    @XmlElement(name = "SourceCharacterSetSpecification", required = true)
    protected CharacterSetSpecificationType sourceCharacterSetSpecification;
    @XmlElement(name = "ToStaticString", required = true)
    protected ToStaticStringType toStaticString;
    @XmlElement(name = "TargetCharacterSetSpecification", required = true)
    protected CharacterSetSpecificationType targetCharacterSetSpecification;
    @XmlElement(name = "FromStaticString", required = true)
    protected FromStaticStringType fromStaticString;
    @XmlElement(name = "TransliterationSource", required = true)
    protected TransliterationSourceType transliterationSource;

    /**
     * Gets the value of the createTranslationStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link CreateTranslationStaticStringType }
     *     
     */
    public CreateTranslationStaticStringType getCreateTranslationStaticString() {
        return createTranslationStaticString;
    }

    /**
     * Sets the value of the createTranslationStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateTranslationStaticStringType }
     *     
     */
    public void setCreateTranslationStaticString(CreateTranslationStaticStringType value) {
        this.createTranslationStaticString = value;
    }

    /**
     * Gets the value of the transliterationName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedNameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedNameType }{@code >}
     *     
     */
    public JAXBElement<SchemaQualifiedNameType> getTransliterationName() {
        return transliterationName;
    }

    /**
     * Sets the value of the transliterationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedNameType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaQualifiedNameType }{@code >}
     *     
     */
    public void setTransliterationName(JAXBElement<SchemaQualifiedNameType> value) {
        this.transliterationName = value;
    }

    /**
     * Gets the value of the forStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link ForStaticStringType }
     *     
     */
    public ForStaticStringType getForStaticString() {
        return forStaticString;
    }

    /**
     * Sets the value of the forStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForStaticStringType }
     *     
     */
    public void setForStaticString(ForStaticStringType value) {
        this.forStaticString = value;
    }

    /**
     * Gets the value of the sourceCharacterSetSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterSetSpecificationType }
     *     
     */
    public CharacterSetSpecificationType getSourceCharacterSetSpecification() {
        return sourceCharacterSetSpecification;
    }

    /**
     * Sets the value of the sourceCharacterSetSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterSetSpecificationType }
     *     
     */
    public void setSourceCharacterSetSpecification(CharacterSetSpecificationType value) {
        this.sourceCharacterSetSpecification = value;
    }

    /**
     * Gets the value of the toStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link ToStaticStringType }
     *     
     */
    public ToStaticStringType getToStaticString() {
        return toStaticString;
    }

    /**
     * Sets the value of the toStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToStaticStringType }
     *     
     */
    public void setToStaticString(ToStaticStringType value) {
        this.toStaticString = value;
    }

    /**
     * Gets the value of the targetCharacterSetSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterSetSpecificationType }
     *     
     */
    public CharacterSetSpecificationType getTargetCharacterSetSpecification() {
        return targetCharacterSetSpecification;
    }

    /**
     * Sets the value of the targetCharacterSetSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterSetSpecificationType }
     *     
     */
    public void setTargetCharacterSetSpecification(CharacterSetSpecificationType value) {
        this.targetCharacterSetSpecification = value;
    }

    /**
     * Gets the value of the fromStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link FromStaticStringType }
     *     
     */
    public FromStaticStringType getFromStaticString() {
        return fromStaticString;
    }

    /**
     * Sets the value of the fromStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromStaticStringType }
     *     
     */
    public void setFromStaticString(FromStaticStringType value) {
        this.fromStaticString = value;
    }

    /**
     * Gets the value of the transliterationSource property.
     * 
     * @return
     *     possible object is
     *     {@link TransliterationSourceType }
     *     
     */
    public TransliterationSourceType getTransliterationSource() {
        return transliterationSource;
    }

    /**
     * Sets the value of the transliterationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransliterationSourceType }
     *     
     */
    public void setTransliterationSource(TransliterationSourceType value) {
        this.transliterationSource = value;
    }

}
