//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UniqueConstraintDefinition_ISO9075ChoiceGroup1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UniqueConstraintDefinition_ISO9075ChoiceGroup1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}UniqueSpecification"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}LeftParen"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}UniqueColumnList"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RightParen"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UniqueConstraintDefinition_ISO9075ChoiceGroup1Type", propOrder = {
    "uniqueSpecification",
    "leftParen",
    "uniqueColumnList",
    "rightParen"
})
public class UniqueConstraintDefinitionISO9075ChoiceGroup1Type {

    @XmlElement(name = "UniqueSpecification", required = true)
    protected UniqueSpecificationType uniqueSpecification;
    @XmlElement(name = "LeftParen", required = true)
    protected String leftParen;
    @XmlElement(name = "UniqueColumnList", required = true)
    protected ColumnNameListType uniqueColumnList;
    @XmlElement(name = "RightParen", required = true)
    protected String rightParen;

    /**
     * Gets the value of the uniqueSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueSpecificationType }
     *     
     */
    public UniqueSpecificationType getUniqueSpecification() {
        return uniqueSpecification;
    }

    /**
     * Sets the value of the uniqueSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueSpecificationType }
     *     
     */
    public void setUniqueSpecification(UniqueSpecificationType value) {
        this.uniqueSpecification = value;
    }

    /**
     * Gets the value of the leftParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftParen() {
        return leftParen;
    }

    /**
     * Sets the value of the leftParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftParen(String value) {
        this.leftParen = value;
    }

    /**
     * Gets the value of the uniqueColumnList property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnNameListType }
     *     
     */
    public ColumnNameListType getUniqueColumnList() {
        return uniqueColumnList;
    }

    /**
     * Sets the value of the uniqueColumnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnNameListType }
     *     
     */
    public void setUniqueColumnList(ColumnNameListType value) {
        this.uniqueColumnList = value;
    }

    /**
     * Gets the value of the rightParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightParen() {
        return rightParen;
    }

    /**
     * Sets the value of the rightParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightParen(String value) {
        this.rightParen = value;
    }

}
