//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateRuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}OnUpdateStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ReferentialAction"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateRuleType", propOrder = {
    "onUpdateStaticString",
    "referentialAction"
})
public class UpdateRuleType {

    @XmlElement(name = "OnUpdateStaticString", required = true)
    protected OnUpdateStaticStringType onUpdateStaticString;
    @XmlElementRef(name = "ReferentialAction", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class)
    protected JAXBElement<ReferentialActionType> referentialAction;

    /**
     * Gets the value of the onUpdateStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link OnUpdateStaticStringType }
     *     
     */
    public OnUpdateStaticStringType getOnUpdateStaticString() {
        return onUpdateStaticString;
    }

    /**
     * Sets the value of the onUpdateStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnUpdateStaticStringType }
     *     
     */
    public void setOnUpdateStaticString(OnUpdateStaticStringType value) {
        this.onUpdateStaticString = value;
    }

    /**
     * Gets the value of the referentialAction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ReferentialActionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ReferentialActionType }{@code >}
     *     
     */
    public JAXBElement<ReferentialActionType> getReferentialAction() {
        return referentialAction;
    }

    /**
     * Sets the value of the referentialAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ReferentialActionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ReferentialActionType }{@code >}
     *     
     */
    public void setReferentialAction(JAXBElement<ReferentialActionType> value) {
        this.referentialAction = value;
    }

}
