//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserDefinedTypeDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDefinedTypeDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}CreateTypeStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}UserDefinedTypeBody"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDefinedTypeDefinitionType", propOrder = {
    "createTypeStaticString",
    "userDefinedTypeBody"
})
public class UserDefinedTypeDefinitionType {

    @XmlElement(name = "CreateTypeStaticString", required = true)
    protected CreateTypeStaticStringType createTypeStaticString;
    @XmlElement(name = "UserDefinedTypeBody", required = true)
    protected UserDefinedTypeBodyType userDefinedTypeBody;

    /**
     * Gets the value of the createTypeStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link CreateTypeStaticStringType }
     *     
     */
    public CreateTypeStaticStringType getCreateTypeStaticString() {
        return createTypeStaticString;
    }

    /**
     * Sets the value of the createTypeStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateTypeStaticStringType }
     *     
     */
    public void setCreateTypeStaticString(CreateTypeStaticStringType value) {
        this.createTypeStaticString = value;
    }

    /**
     * Gets the value of the userDefinedTypeBody property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedTypeBodyType }
     *     
     */
    public UserDefinedTypeBodyType getUserDefinedTypeBody() {
        return userDefinedTypeBody;
    }

    /**
     * Sets the value of the userDefinedTypeBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedTypeBodyType }
     *     
     */
    public void setUserDefinedTypeBody(UserDefinedTypeBodyType value) {
        this.userDefinedTypeBody = value;
    }

}
