//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViewElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}SelfReferencingColumnSpecification"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}ViewColumnOption"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewElementType", propOrder = {
    "selfReferencingColumnSpecificationOrViewColumnOption"
})
public class ViewElementType {

    @XmlElements({
        @XmlElement(name = "SelfReferencingColumnSpecification", type = SelfReferencingColumnSpecificationType.class),
        @XmlElement(name = "ViewColumnOption", type = ViewColumnOptionType.class)
    })
    protected Object selfReferencingColumnSpecificationOrViewColumnOption;

    /**
     * Gets the value of the selfReferencingColumnSpecificationOrViewColumnOption property.
     * 
     * @return
     *     possible object is
     *     {@link SelfReferencingColumnSpecificationType }
     *     {@link ViewColumnOptionType }
     *     
     */
    public Object getSelfReferencingColumnSpecificationOrViewColumnOption() {
        return selfReferencingColumnSpecificationOrViewColumnOption;
    }

    /**
     * Sets the value of the selfReferencingColumnSpecificationOrViewColumnOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelfReferencingColumnSpecificationType }
     *     {@link ViewColumnOptionType }
     *     
     */
    public void setSelfReferencingColumnSpecificationOrViewColumnOption(Object value) {
        this.selfReferencingColumnSpecificationOrViewColumnOption = value;
    }

}
