//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WhileStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WhileStatementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}BeginningLabel" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}Colon" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}WhileStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SearchCondition"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DoStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SqlStatementList"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}EndWhileStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}EndingLabel" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WhileStatementType", propOrder = {
    "beginningLabel",
    "colon",
    "whileStaticString",
    "searchCondition",
    "doStaticString",
    "sqlStatementList",
    "endWhileStaticString",
    "endingLabel"
})
public class WhileStatementType {

    @XmlElement(name = "BeginningLabel")
    protected ActualIdentifierType beginningLabel;
    @XmlElement(name = "Colon")
    protected String colon;
    @XmlElement(name = "WhileStaticString", required = true)
    protected WhileStaticStringType whileStaticString;
    @XmlElement(name = "SearchCondition", required = true)
    protected BooleanValueExpressionType searchCondition;
    @XmlElement(name = "DoStaticString", required = true)
    protected DoStaticStringType doStaticString;
    @XmlElement(name = "SqlStatementList", required = true)
    protected SqlStatementListType sqlStatementList;
    @XmlElement(name = "EndWhileStaticString", required = true)
    protected EndWhileStaticStringType endWhileStaticString;
    @XmlElement(name = "EndingLabel")
    protected ActualIdentifierType endingLabel;

    /**
     * Gets the value of the beginningLabel property.
     * 
     * @return
     *     possible object is
     *     {@link ActualIdentifierType }
     *     
     */
    public ActualIdentifierType getBeginningLabel() {
        return beginningLabel;
    }

    /**
     * Sets the value of the beginningLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualIdentifierType }
     *     
     */
    public void setBeginningLabel(ActualIdentifierType value) {
        this.beginningLabel = value;
    }

    /**
     * Gets the value of the colon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColon() {
        return colon;
    }

    /**
     * Sets the value of the colon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColon(String value) {
        this.colon = value;
    }

    /**
     * Gets the value of the whileStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link WhileStaticStringType }
     *     
     */
    public WhileStaticStringType getWhileStaticString() {
        return whileStaticString;
    }

    /**
     * Sets the value of the whileStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhileStaticStringType }
     *     
     */
    public void setWhileStaticString(WhileStaticStringType value) {
        this.whileStaticString = value;
    }

    /**
     * Gets the value of the searchCondition property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanValueExpressionType }
     *     
     */
    public BooleanValueExpressionType getSearchCondition() {
        return searchCondition;
    }

    /**
     * Sets the value of the searchCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanValueExpressionType }
     *     
     */
    public void setSearchCondition(BooleanValueExpressionType value) {
        this.searchCondition = value;
    }

    /**
     * Gets the value of the doStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link DoStaticStringType }
     *     
     */
    public DoStaticStringType getDoStaticString() {
        return doStaticString;
    }

    /**
     * Sets the value of the doStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoStaticStringType }
     *     
     */
    public void setDoStaticString(DoStaticStringType value) {
        this.doStaticString = value;
    }

    /**
     * Gets the value of the sqlStatementList property.
     * 
     * @return
     *     possible object is
     *     {@link SqlStatementListType }
     *     
     */
    public SqlStatementListType getSqlStatementList() {
        return sqlStatementList;
    }

    /**
     * Sets the value of the sqlStatementList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlStatementListType }
     *     
     */
    public void setSqlStatementList(SqlStatementListType value) {
        this.sqlStatementList = value;
    }

    /**
     * Gets the value of the endWhileStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link EndWhileStaticStringType }
     *     
     */
    public EndWhileStaticStringType getEndWhileStaticString() {
        return endWhileStaticString;
    }

    /**
     * Sets the value of the endWhileStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndWhileStaticStringType }
     *     
     */
    public void setEndWhileStaticString(EndWhileStaticStringType value) {
        this.endWhileStaticString = value;
    }

    /**
     * Gets the value of the endingLabel property.
     * 
     * @return
     *     possible object is
     *     {@link ActualIdentifierType }
     *     
     */
    public ActualIdentifierType getEndingLabel() {
        return endingLabel;
    }

    /**
     * Sets the value of the endingLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualIdentifierType }
     *     
     */
    public void setEndingLabel(ActualIdentifierType value) {
        this.endingLabel = value;
    }

}
