//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WindowPartitionColumnReferenceListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindowPartitionColumnReferenceListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}WindowPartitionColumnReference"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}CommaWindowPartitionColumnReferenceItemtype" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindowPartitionColumnReferenceListType", propOrder = {
    "windowPartitionColumnReference",
    "commaWindowPartitionColumnReferenceItemtype"
})
public class WindowPartitionColumnReferenceListType {

    @XmlElement(name = "WindowPartitionColumnReference", required = true)
    protected WindowPartitionColumnReferenceType windowPartitionColumnReference;
    @XmlElement(name = "CommaWindowPartitionColumnReferenceItemtype")
    protected List<CommaWindowPartitionColumnReferenceItemtypeType> commaWindowPartitionColumnReferenceItemtype;

    /**
     * Gets the value of the windowPartitionColumnReference property.
     * 
     * @return
     *     possible object is
     *     {@link WindowPartitionColumnReferenceType }
     *     
     */
    public WindowPartitionColumnReferenceType getWindowPartitionColumnReference() {
        return windowPartitionColumnReference;
    }

    /**
     * Sets the value of the windowPartitionColumnReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowPartitionColumnReferenceType }
     *     
     */
    public void setWindowPartitionColumnReference(WindowPartitionColumnReferenceType value) {
        this.windowPartitionColumnReference = value;
    }

    /**
     * Gets the value of the commaWindowPartitionColumnReferenceItemtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commaWindowPartitionColumnReferenceItemtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommaWindowPartitionColumnReferenceItemtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommaWindowPartitionColumnReferenceItemtypeType }
     * 
     * 
     */
    public List<CommaWindowPartitionColumnReferenceItemtypeType> getCommaWindowPartitionColumnReferenceItemtype() {
        if (commaWindowPartitionColumnReferenceItemtype == null) {
            commaWindowPartitionColumnReferenceItemtype = new ArrayList<CommaWindowPartitionColumnReferenceItemtypeType>();
        }
        return this.commaWindowPartitionColumnReferenceItemtype;
    }

}
