//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WindowFrameClauseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindowFrameClauseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}WindowFrameUnits"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}WindowFrameExtent"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}WindowFrameExclusion" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindowFrameClauseType", propOrder = {
    "windowFrameUnits",
    "windowFrameExtent",
    "windowFrameExclusion"
})
public class WindowFrameClauseType {

    @XmlElement(name = "WindowFrameUnits", required = true)
    protected WindowFrameUnitsType windowFrameUnits;
    @XmlElement(name = "WindowFrameExtent", required = true)
    protected WindowFrameExtentType windowFrameExtent;
    @XmlElement(name = "WindowFrameExclusion")
    protected WindowFrameExclusionType windowFrameExclusion;

    /**
     * Gets the value of the windowFrameUnits property.
     * 
     * @return
     *     possible object is
     *     {@link WindowFrameUnitsType }
     *     
     */
    public WindowFrameUnitsType getWindowFrameUnits() {
        return windowFrameUnits;
    }

    /**
     * Sets the value of the windowFrameUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowFrameUnitsType }
     *     
     */
    public void setWindowFrameUnits(WindowFrameUnitsType value) {
        this.windowFrameUnits = value;
    }

    /**
     * Gets the value of the windowFrameExtent property.
     * 
     * @return
     *     possible object is
     *     {@link WindowFrameExtentType }
     *     
     */
    public WindowFrameExtentType getWindowFrameExtent() {
        return windowFrameExtent;
    }

    /**
     * Sets the value of the windowFrameExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowFrameExtentType }
     *     
     */
    public void setWindowFrameExtent(WindowFrameExtentType value) {
        this.windowFrameExtent = value;
    }

    /**
     * Gets the value of the windowFrameExclusion property.
     * 
     * @return
     *     possible object is
     *     {@link WindowFrameExclusionType }
     *     
     */
    public WindowFrameExclusionType getWindowFrameExclusion() {
        return windowFrameExclusion;
    }

    /**
     * Sets the value of the windowFrameExclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowFrameExclusionType }
     *     
     */
    public void setWindowFrameExclusion(WindowFrameExclusionType value) {
        this.windowFrameExclusion = value;
    }

}
