//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlCharacterStringSerializationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlCharacterStringSerializationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlserializeStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}LeftParen"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DocumentOrContentOrSequence"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlValueExpression"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}AsStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DataType"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlSerializeVersion" minOccurs="0"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RightParen"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlCharacterStringSerializationType", propOrder = {
    "xmlserializeStaticString",
    "leftParen",
    "documentOrContentOrSequence",
    "xmlValueExpression",
    "asStaticString",
    "dataType",
    "xmlSerializeVersion",
    "rightParen"
})
public class XmlCharacterStringSerializationType {

    @XmlElement(name = "XmlserializeStaticString", required = true)
    protected XmlserializeStaticStringType xmlserializeStaticString;
    @XmlElement(name = "LeftParen", required = true)
    protected String leftParen;
    @XmlElement(name = "DocumentOrContentOrSequence", required = true)
    protected DocumentOrContentOrSequenceType documentOrContentOrSequence;
    @XmlElement(name = "XmlValueExpression", required = true)
    protected XmlPrimaryType xmlValueExpression;
    @XmlElement(name = "AsStaticString", required = true)
    protected AsStaticStringType asStaticString;
    @XmlElementRef(name = "DataType", namespace = "http://www.devspringsoftware.com", type = JAXBElement.class)
    protected JAXBElement<DataTypeType> dataType;
    @XmlElement(name = "XmlSerializeVersion")
    protected XmlSerializeVersionType xmlSerializeVersion;
    @XmlElement(name = "RightParen", required = true)
    protected String rightParen;

    /**
     * Gets the value of the xmlserializeStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link XmlserializeStaticStringType }
     *     
     */
    public XmlserializeStaticStringType getXmlserializeStaticString() {
        return xmlserializeStaticString;
    }

    /**
     * Sets the value of the xmlserializeStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlserializeStaticStringType }
     *     
     */
    public void setXmlserializeStaticString(XmlserializeStaticStringType value) {
        this.xmlserializeStaticString = value;
    }

    /**
     * Gets the value of the leftParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftParen() {
        return leftParen;
    }

    /**
     * Sets the value of the leftParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftParen(String value) {
        this.leftParen = value;
    }

    /**
     * Gets the value of the documentOrContentOrSequence property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentOrContentOrSequenceType }
     *     
     */
    public DocumentOrContentOrSequenceType getDocumentOrContentOrSequence() {
        return documentOrContentOrSequence;
    }

    /**
     * Sets the value of the documentOrContentOrSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentOrContentOrSequenceType }
     *     
     */
    public void setDocumentOrContentOrSequence(DocumentOrContentOrSequenceType value) {
        this.documentOrContentOrSequence = value;
    }

    /**
     * Gets the value of the xmlValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link XmlPrimaryType }
     *     
     */
    public XmlPrimaryType getXmlValueExpression() {
        return xmlValueExpression;
    }

    /**
     * Sets the value of the xmlValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlPrimaryType }
     *     
     */
    public void setXmlValueExpression(XmlPrimaryType value) {
        this.xmlValueExpression = value;
    }

    /**
     * Gets the value of the asStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link AsStaticStringType }
     *     
     */
    public AsStaticStringType getAsStaticString() {
        return asStaticString;
    }

    /**
     * Sets the value of the asStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsStaticStringType }
     *     
     */
    public void setAsStaticString(AsStaticStringType value) {
        this.asStaticString = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}
     *     
     */
    public JAXBElement<DataTypeType> getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DataTypeType }{@code >}
     *     
     */
    public void setDataType(JAXBElement<DataTypeType> value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the xmlSerializeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link XmlSerializeVersionType }
     *     
     */
    public XmlSerializeVersionType getXmlSerializeVersion() {
        return xmlSerializeVersion;
    }

    /**
     * Sets the value of the xmlSerializeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlSerializeVersionType }
     *     
     */
    public void setXmlSerializeVersion(XmlSerializeVersionType value) {
        this.xmlSerializeVersion = value;
    }

    /**
     * Gets the value of the rightParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightParen() {
        return rightParen;
    }

    /**
     * Sets the value of the rightParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightParen(String value) {
        this.rightParen = value;
    }

}
