//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlCastSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlCastSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlcastStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}LeftParen"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlCastOperand"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}AsStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlCastTarget"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RightParen"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlCastSpecificationType", propOrder = {
    "xmlcastStaticString",
    "leftParen",
    "xmlCastOperand",
    "asStaticString",
    "xmlCastTarget",
    "rightParen"
})
public class XmlCastSpecificationType {

    @XmlElement(name = "XmlcastStaticString", required = true)
    protected XmlcastStaticStringType xmlcastStaticString;
    @XmlElement(name = "LeftParen", required = true)
    protected String leftParen;
    @XmlElement(name = "XmlCastOperand", required = true)
    protected XmlCastOperandType xmlCastOperand;
    @XmlElement(name = "AsStaticString", required = true)
    protected AsStaticStringType asStaticString;
    @XmlElement(name = "XmlCastTarget", required = true)
    protected XmlCastTargetType xmlCastTarget;
    @XmlElement(name = "RightParen", required = true)
    protected String rightParen;

    /**
     * Gets the value of the xmlcastStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link XmlcastStaticStringType }
     *     
     */
    public XmlcastStaticStringType getXmlcastStaticString() {
        return xmlcastStaticString;
    }

    /**
     * Sets the value of the xmlcastStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlcastStaticStringType }
     *     
     */
    public void setXmlcastStaticString(XmlcastStaticStringType value) {
        this.xmlcastStaticString = value;
    }

    /**
     * Gets the value of the leftParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftParen() {
        return leftParen;
    }

    /**
     * Sets the value of the leftParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftParen(String value) {
        this.leftParen = value;
    }

    /**
     * Gets the value of the xmlCastOperand property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCastOperandType }
     *     
     */
    public XmlCastOperandType getXmlCastOperand() {
        return xmlCastOperand;
    }

    /**
     * Sets the value of the xmlCastOperand property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCastOperandType }
     *     
     */
    public void setXmlCastOperand(XmlCastOperandType value) {
        this.xmlCastOperand = value;
    }

    /**
     * Gets the value of the asStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link AsStaticStringType }
     *     
     */
    public AsStaticStringType getAsStaticString() {
        return asStaticString;
    }

    /**
     * Sets the value of the asStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsStaticStringType }
     *     
     */
    public void setAsStaticString(AsStaticStringType value) {
        this.asStaticString = value;
    }

    /**
     * Gets the value of the xmlCastTarget property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCastTargetType }
     *     
     */
    public XmlCastTargetType getXmlCastTarget() {
        return xmlCastTarget;
    }

    /**
     * Sets the value of the xmlCastTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCastTargetType }
     *     
     */
    public void setXmlCastTarget(XmlCastTargetType value) {
        this.xmlCastTarget = value;
    }

    /**
     * Gets the value of the rightParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightParen() {
        return rightParen;
    }

    /**
     * Sets the value of the rightParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightParen(String value) {
        this.rightParen = value;
    }

}
