//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlParseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlParseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlparseStaticString"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}LeftParen"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}DocumentOrContent"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}StringValueExpression"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlWhitespaceOption"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}RightParen"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlParseType", propOrder = {
    "xmlparseStaticString",
    "leftParen",
    "documentOrContent",
    "stringValueExpression",
    "xmlWhitespaceOption",
    "rightParen"
})
public class XmlParseType {

    @XmlElement(name = "XmlparseStaticString", required = true)
    protected XmlparseStaticStringType xmlparseStaticString;
    @XmlElement(name = "LeftParen", required = true)
    protected String leftParen;
    @XmlElement(name = "DocumentOrContent", required = true)
    protected DocumentOrContentType documentOrContent;
    @XmlElement(name = "StringValueExpression", required = true)
    protected StringValueExpressionType stringValueExpression;
    @XmlElement(name = "XmlWhitespaceOption", required = true)
    protected XmlWhitespaceOptionType xmlWhitespaceOption;
    @XmlElement(name = "RightParen", required = true)
    protected String rightParen;

    /**
     * Gets the value of the xmlparseStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link XmlparseStaticStringType }
     *     
     */
    public XmlparseStaticStringType getXmlparseStaticString() {
        return xmlparseStaticString;
    }

    /**
     * Sets the value of the xmlparseStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlparseStaticStringType }
     *     
     */
    public void setXmlparseStaticString(XmlparseStaticStringType value) {
        this.xmlparseStaticString = value;
    }

    /**
     * Gets the value of the leftParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftParen() {
        return leftParen;
    }

    /**
     * Sets the value of the leftParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftParen(String value) {
        this.leftParen = value;
    }

    /**
     * Gets the value of the documentOrContent property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentOrContentType }
     *     
     */
    public DocumentOrContentType getDocumentOrContent() {
        return documentOrContent;
    }

    /**
     * Sets the value of the documentOrContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentOrContentType }
     *     
     */
    public void setDocumentOrContent(DocumentOrContentType value) {
        this.documentOrContent = value;
    }

    /**
     * Gets the value of the stringValueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueExpressionType }
     *     
     */
    public StringValueExpressionType getStringValueExpression() {
        return stringValueExpression;
    }

    /**
     * Sets the value of the stringValueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueExpressionType }
     *     
     */
    public void setStringValueExpression(StringValueExpressionType value) {
        this.stringValueExpression = value;
    }

    /**
     * Gets the value of the xmlWhitespaceOption property.
     * 
     * @return
     *     possible object is
     *     {@link XmlWhitespaceOptionType }
     *     
     */
    public XmlWhitespaceOptionType getXmlWhitespaceOption() {
        return xmlWhitespaceOption;
    }

    /**
     * Sets the value of the xmlWhitespaceOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlWhitespaceOptionType }
     *     
     */
    public void setXmlWhitespaceOption(XmlWhitespaceOptionType value) {
        this.xmlWhitespaceOption = value;
    }

    /**
     * Gets the value of the rightParen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightParen() {
        return rightParen;
    }

    /**
     * Sets the value of the rightParen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightParen(String value) {
        this.rightParen = value;
    }

}
