//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 08:58:47 PM EDT 
//


package com.devspringsoftware.xml.ssqml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlTypeModifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlTypeModifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.devspringsoftware.com}XmlTypeModifier_ISO9075ChoiceGroup1"/>
 *         &lt;element ref="{http://www.devspringsoftware.com}SequenceStaticString"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlTypeModifierType", propOrder = {
    "xmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString"
})
public class XmlTypeModifierType {

    @XmlElements({
        @XmlElement(name = "XmlTypeModifier_ISO9075ChoiceGroup1", type = XmlTypeModifierISO9075ChoiceGroup1Type.class),
        @XmlElement(name = "SequenceStaticString", type = SequenceStaticStringType.class)
    })
    protected Object xmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString;

    /**
     * Gets the value of the xmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTypeModifierISO9075ChoiceGroup1Type }
     *     {@link SequenceStaticStringType }
     *     
     */
    public Object getXmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString() {
        return xmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString;
    }

    /**
     * Sets the value of the xmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTypeModifierISO9075ChoiceGroup1Type }
     *     {@link SequenceStaticStringType }
     *     
     */
    public void setXmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString(Object value) {
        this.xmlTypeModifierISO9075ChoiceGroup1OrSequenceStaticString = value;
    }

}
